name: referi_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #Responsiveness
  sizer: ^2.0.15
  auto_size_text: ^3.0.0

  #Funtionalities
  image_picker: ^0.8.5+3
  mobile_scanner: ^2.0.0

  #Visuals
  badges: ^2.0.3
  fluttertoast: ^8.1.1
  pin_code_fields: ^7.4.0
  flutter_native_splash: ^2.2.9
  flutter_custom_clippers: ^2.0.0

  #Utils
  dio: ^4.0.6
  intl: ^0.17.0
  provider: ^6.0.3
  location: ^4.4.0
  animate_do: ^2.1.0
  icons_launcher: ^2.0.4
  flutter_image_compress: ^1.1.3
  flutter_credit_card: ^3.0.4

  # change_app_package_name:
  # cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # flutter_launcher_icons: "^0.10.0"

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/card_images/
    - assets/images/clubs/
    - assets/logo/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

#flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#FF9800"
  image: assets/logo/logo_splash_900x900.png

  android_12:
    color: "#FF9800"
    image: assets/logo/logo_splash_900x900.png

  android: true
  fullscreen: true

#flutter pub run flutter_launcher_icons:main
# flutter_icons:
#   android: true
#   ios: false
#   image_path: "assets/logo/logo_900x900.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   adaptive_icon_background: '#FF9800'
#   adaptive_icon_foreground: "assets/logo/logo_900x900.png"
#   adaptive_icon_round: "assets/logo/logo_launch_108x108.png"
#   web:
#     generate: false
#   windows:
#     generate: false

icons_launcher:
  # image_path: 'assets/logo/logo_launch_108x108.png'
  platforms:
    android:
      enable: true
      image_path: "assets/logo/logo_900x900.png"
      # adaptive_background_color: '#FF9800'
      adaptive_background_image: "assets/logo/logo_900x900.png"
      adaptive_foreground_image: "assets/logo/logo_900x900.png"
      adaptive_round_image: "assets/logo/logo_900x900.png"
    # ios:
    #   enable: false
    #   image_path: 'assets/ic_logo_rectangle.png'
    # web:
    #   enable: false
    #   image_path: 'assets/ic_logo_border.png'
    #   favicon_path: 'assets/ic_logo_round.png'
    # macos:
    #   enable: false
    #   image_path: 'assets/ic_logo_border.png'
    # windows:
    #   enable: false
    #   image_path: 'assets/ic_logo_border.png'
    # linux:
    #   enable: false
    #   image_path: 'assets/ic_logo_border.png'
